# Generated by Django 3.0.4 on 2020-05-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natparks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatParkGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kohdeLat', models.DecimalField(decimal_places=10, default=64.12, max_digits=12)),
                ('kohdeLon', models.DecimalField(decimal_places=10, default=25.12, max_digits=12)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natparks.NatParks')),
            ],
        ),
    ]
