# Generated by Django 3.0.4 on 2020-05-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natparks', '0002_natparkgeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natparkgeo',
            name='kohdeLat',
            field=models.DecimalField(decimal_places=8, default=64.12, max_digits=10),
        ),
        migrations.AlterField(
            model_name='natparkgeo',
            name='kohdeLon',
            field=models.DecimalField(decimal_places=8, default=-108.12, max_digits=12),
        ),
    ]
