# Generated by Django 3.1.3 on 2020-11-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natparks', '0005_natparkgeo_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natparks',
            old_name='description',
            new_name='ndescription',
        ),
        migrations.RenameField(
            model_name='natparks',
            old_name='location',
            new_name='nlocation',
        ),
        migrations.RenameField(
            model_name='natparks',
            old_name='picture',
            new_name='npicture',
        ),
        migrations.RenameField(
            model_name='natparks',
            old_name='title',
            new_name='ntitle',
        ),
    ]
