# Generated by Django 3.1.3 on 2020-11-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natparks', '0007_auto_20201114_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='natparkgeo',
            name='place',
            field=models.CharField(blank=True, default='paikka', max_length=128),
        ),
        migrations.AddField(
            model_name='natparkgeo',
            name='state',
            field=models.CharField(blank=True, default='osav', max_length=128),
        ),
    ]
